# Generated by Django 3.0.5 on 2020-07-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='accNo',
            field=models.IntegerField(max_length=100),
        ),
    ]
