# Generated by Django 3.0.5 on 2020-07-20 11:28

from django.db import migrations, models
import payslip.models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip', '0002_auto_20200720_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='accNo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default=payslip.models.id_generator, max_length=100, primary_key=True, serialize=False),
        ),
    ]
