# Generated by Django 3.0.5 on 2020-07-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip', '0003_auto_20200720_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ca',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='ma',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='sa',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='basic',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='leaves_allowed',
            field=models.IntegerField(default=3),
        ),
    ]
